version: "3.8"
services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
      - neo4j

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zoho
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/pass
    ports:
      - "7474:7474"
      - "7687:7687" 